[package]
name = "block_two"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "block_two"


[dependencies]
chrono = "0.4.2"
sha256="1.5.0"